api: none
api-version: "1.15"
name: Utilities
version: "1.0"
author: PoC4
main: fr.neolithic.utilities.Main
commands:
  sethome:
    description: "Set a home for you to teleport to later"
    permission: utilities.sethome
  delhome:
    description: "Delete the specified home"
    permission: utilities.delhome
  home:
    description: "Teleport you to the specified home"
    permission: utilities.home
  homes:
    description: "List your homes"
    permission: utilities.homes
  bed:
    description: "Teleport you to your bed"
    permission: utilities.bed
  setspawn:
    description: "Set the spawn location"
    permission: utilities.setspawn
  delspawn:
    description: "Delete the spawn"
    permission: utilities.delspawn
  spawn:
    description: "Teleport you to spawn"
    permission: utilities.spawn
  back:
    description: "Teleport you back to your last location"
    permission: utilities.back
  fly:
    description: "Toggle fly"
    permission: utilities.fly
  god:
    description: "Toggle godmode"
    permission: utilities.god
  heal:
    description: "heal yourself"
    permission: utilities.heal
  feed:
    description: "feed yourself"
    permission: utilities.feed
