api: none
api-version: "1.15"
name: Utilities
version: "1.0"
author: PoC4
main: fr.neolithic.utilities.Main
commands:
  addmaxhomes:
    description: "Add one or the specified amount of max homes to a player"
    permission: utilities.addmaxhomes
  subtractmaxhomes:
    description: "Substract one or the specified amount of max homes to a player"
    permission: utilities.subtractmaxhomes
  setmaxhomes:
    description: "Set the max homes amount of a player"
    permission: utilities.setmaxhomes
  resetmaxhomes:
    description: "Reset the max homes amount of a player"
    permission: utilities.resetmaxhomes
  sethome:
    description: "Set a home for you to teleport to later"
    permission: utilities.sethome
  delhome:
    description: "Delete the specified home"
    permission: utilities.delhome
  home:
    description: "Teleport you to the specified home"
    permission: utilities.home
  homes:
    description: "List your homes"
    permission: utilities.homes
  bed:
    description: "Teleport you to your bed"
    permission: utilities.bed
  setspawn:
    description: "Set the spawn location"
    permission: utilities.setspawn
  delspawn:
    description: "Delete the spawn"
    permission: utilities.delspawn
  spawn:
    description: "Teleport you to spawn"
    permission: utilities.spawn
  back:
    description: "Teleport you back to your last location"
    permission: utilities.back
  fly:
    description: "Toggle fly"
    permission: utilities.fly
  flyspeed:
    description: "Set your fly speed or the fly speed of an other player"
    permission: utilities.flyspeed
  god:
    description: "Toggle godmode"
    permission: utilities.god
  heal:
    description: "Heal yourself or a targeted player"
    permission: utilities.heal
  feed:
    description: "Feed yourself or a targeted player"
    permission: utilities.feed
  gm:
    description: "Change your gamemode or the gamemode of another player"
    permission: utilities.gamemode
  gms:
    description: "Set your gamemode or the gamemode of another player to survival"
    permission: utilities.gamemode
  gmc:
    description: "Set your gamemode or the gamemode of another player to creative"
    permission: utilities.gamemode
  gma:
    description: "Set your gamemode or the gamemode of another player to adventure"
    permission: utilities.gamemode
  gmsp:
    description: "Set your gamemode or the gamemode of another player to spectator"
    permission: utilities.gamemode
permissions:
  utilities.*:
    default: false
    children:
      utilities.addmaxhomes:
        default: op
      utilities.subtractmaxhomes:
        default: op
      utilities.setmaxhomes:
        default: op
      utilities.resetmaxhomes:
        default: op
      utilities.maxhomes.unlimited:
        default: op
      utilities.sethome:
        default: true
      utilities.delhome:
        default: true
      utilities.homes:
        default: true
      utilities.home:
        default: true
      utilities.bed:
        default: true
      utilities.setspawn:
        default: op
      utilities.delspawn:
        default: op
      utilities.spawn:
        default: true
      utilities.back:
        default: true
      utilities.back.ondeath:
        default: true
      utilities.fly:
        default: op
      utilities.flyspeed:
        default: op
      utilities.god:
        default: op
      utilities.heal:
        default: op
      utilities.feed:
        default: op
      utilities.gamemode:
        default: op
